const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises');
(async()=>{
 const {createServer}=await import('vite'),server=await createServer({server:{host:'127.0.0.1',port:4187,strictPort:true}});await server.listen();
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai'}),page=await context.newPage(),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));
 const out=process.env.MOBILE_QA_DIR||'/tmp/connections-qa';await fs.mkdir(out,{recursive:true});
 const json=value=>({status:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify(value)});
 await page.route('https://restapi.amap.com/**',route=>{requests.push('amap');return route.fulfill(json({status:'1',pois:[{id:'a',name:'贵阳测试餐厅',cityname:'贵阳',address:'南街 1 号',location:'106.6,26.6'},{id:'b',name:'贵阳测试餐厅',cityname:'贵阳',address:'北街 2 号',location:'106.7,26.7'}]}));});
 await page.route('https://api.nal.usda.gov/**',route=>{requests.push('usda');return route.fulfill(json({foods:[{fdcId:42,description:'Chicken breast, roasted',dataType:'Foundation',foodNutrients:[{nutrientId:1008,unitName:'KCAL',value:165}]}]}));});
 await page.route('https://world.openfoodfacts.org/**',route=>{requests.push('off');return route.fulfill(json({code:'6901234567890',product:{code:'6901234567890',product_name_zh:'测试牛奶',brands:'测试品牌',product_quantity_unit:'ml',nutriments:{'energy-kcal_100g':46}}}));});
 const workspace=()=>page.evaluate(async()=>(await(await import('/src/services/durableStore.ts')).loadWorkspace()).data);
 const health=()=>page.evaluate(async()=>(await(await import('/src/services/health/store.ts')).readHealth()).records);
 const wait=async(check)=>{const until=Date.now()+10000;while(!await check()){if(Date.now()>until)throw Error('durable state timeout');await new Promise(r=>setTimeout(r,50));}};
 try{
  await page.goto('http://127.0.0.1:4187');await page.locator('.m-workspace').waitFor();
  await page.evaluate(async()=>{const c=await import('/src/services/connections/store.ts'),s=await c.loadConnections();s.settings.city='贵阳';s.secrets.amap_key='fixture-map-key';s.secrets.usda_key='fixture-usda-key';await c.saveConnections(s);});
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('todotree:journal')));await page.getByRole('button',{name:'开始记录',exact:true}).click();
  await page.getByLabel('事情描述',{exact:true}).fill('探店来源测试');await page.locator('.j-photo-actions').getByRole('button',{name:'地点',exact:true}).click();await page.getByLabel('地点搜索关键词').fill('贵阳测试餐厅');assert.equal(requests.length,0,'typing never queries');
  await page.getByRole('button',{name:'查询门店',exact:true}).click();await page.locator('.place-result').nth(1).click();assert.equal(requests.length,1);assert.equal(await page.getByLabel('确认地点名称').inputValue(),'贵阳测试餐厅');await page.getByRole('button',{name:'确认使用这个地点'}).click();
  await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('.j-editor').waitFor({state:'hidden'});
  const place=await page.evaluate(async()=>(await(await import('/src/services/journal/store.ts')).journal.list({})).entries[0].place);assert.equal(place.source_id,'b');assert.equal(place.address,'北街 2 号');assert.equal(place.coordinate_system,'GCJ-02');assert.ok(place.confirmed_at);
  await page.locator('.j-shell > .app-mode-switch').getByRole('button',{name:'健康',exact:true}).click();await page.getByRole('button',{name:'饮食 记一餐',exact:true}).click();
  await page.getByLabel('食物名称',{exact:true}).fill('鸡胸肉');assert.equal(requests.length,1);await page.getByRole('button',{name:'查询食品来源',exact:true}).click();await page.locator('.h-food-results button').first().click();await page.getByLabel('食物克重',{exact:true}).fill('150');await page.getByRole('button',{name:'收藏这份营养标签'}).click();await page.getByText('已保存个人标签',{exact:false}).waitFor();
  await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('.h-editor').waitFor({state:'hidden'});let records=await health();assert.equal(records.find(r=>r.kind==='intake').body.kcal,247.5);
  await page.getByRole('button',{name:/^饮食 /}).click();await page.getByLabel('食品查询来源').selectOption('off');await page.getByLabel('食物名称',{exact:true}).fill('6901234567890');await page.getByRole('button',{name:'查询食品来源',exact:true}).click();await page.locator('.h-food-results button').first().click();await page.getByLabel('食物克重',{exact:true}).fill('250');await page.getByRole('button',{name:'保存',exact:true}).click();await page.locator('.h-editor').waitFor({state:'hidden'});records=await health();const milk=records.find(r=>r.kind==='intake'&&r.body.food.barcode);assert.equal(milk.body.kcal,null);assert.equal(milk.body.food.label_energy.basis,'100ml');
  await page.getByRole('button',{name:/^饮食 /}).click();await page.getByLabel('食品查询来源').selectOption('personal');await page.getByLabel('食物名称',{exact:true}).fill('Chicken');await page.getByRole('button',{name:'查询食品来源',exact:true}).click();await page.locator('.h-food-results button').first().waitFor();assert.equal(requests.length,3,'personal search remains offline');
  await page.getByRole('button',{name:'来源设置',exact:true}).click();await page.locator('.connection-dialog').waitFor();for(const width of [320,393,430]){await page.setViewportSize({width,height:852});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:`${out}/connections-${width}.png`});}
  await page.evaluate(()=>window.dispatchEvent(new Event('todotree:back',{cancelable:true})));await page.locator('.connection-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.h-editor').count(),1,'nested back closes configuration only');await page.getByRole('button',{name:'返回健康并保留草稿'}).click();await page.locator('.h-editor').waitFor({state:'hidden'});
  // Public preferences use a real IndexedDB compare-and-swap across tabs.
  const second=await context.newPage();await second.goto('http://127.0.0.1:4187');const [a,b]=await Promise.all([page.evaluate(async()=>(await import('/src/services/connections/store.ts')).loadConnections()),second.evaluate(async()=>(await import('/src/services/connections/store.ts')).loadConnections())]);assert.equal(a.revision,b.revision);
  await page.evaluate(async s=>{const c=await import('/src/services/connections/store.ts');s.settings.city='更新城市';await c.saveConnections(s);},a);const conflict=await second.evaluate(async s=>{try{await(await import('/src/services/connections/store.ts')).saveConnections(s);return '';}catch(e){return e.message;}},b);assert.match(conflict,/另一页面/);await second.close();
  await page.reload();await page.locator('.h-shell').waitFor();assert.equal((await health()).filter(r=>r.kind==='intake').length,2);const stored=await page.evaluate(async()=>(await import('/src/services/connections/store.ts')).loadConnections());assert.equal(stored.settings.foods.length,1);
  await page.locator('.h-shell > .app-mode-switch').getByRole('button',{name:'待办',exact:true}).click();await page.locator('.m-workspace').waitFor();
  await page.evaluate(()=>window.dispatchEvent(new CustomEvent('todotree:journal')));await page.locator('.j-shell').waitFor();await page.getByRole('button',{name:'＋ 记一笔',exact:true}).click();await page.getByLabel('事情描述',{exact:true}).fill('通知跳转前的即时草稿');await page.evaluate(()=>window.dispatchEvent(new CustomEvent('todotree:mode',{detail:{mode:'tasks'}})));await page.locator('.j-shell').waitFor({state:'hidden'});
  const draft=await page.evaluate(async()=>(await(await import('/src/services/journal/store.ts')).journal.boot()).drafts.find(d=>d.entry.description==='通知跳转前的即时草稿'));assert.ok(draft,'navigation flushes the editor without waiting for the 800 ms timer');
  await page.getByRole('textbox',{name:'任务标题',exact:true}).fill('提醒回归任务');await page.getByRole('button',{name:'保存任务',exact:true}).click();await wait(async()=>(await workspace()).tasks.some(t=>t.title==='提醒回归任务'));
  await page.getByRole('button',{name:'更多操作 提醒回归任务',exact:true}).click();await page.getByRole('button',{name:'查看详情 / 调整截止日期',exact:true}).click();await page.getByLabel('待办提醒时刻').fill('2099-01-01T12:00');await page.getByRole('button',{name:'保存本次提醒'}).click();await wait(async()=>(await workspace()).tasks.find(t=>t.title==='提醒回归任务')?.reminder?.enabled);
  const before=await workspace();assert.equal(before.tasks.find(t=>t.title==='提醒回归任务').reminder.channels[0],'local');const snapshot=await page.evaluate(async()=>{const c=await import('/src/services/durableStore.ts');return JSON.parse(await c.exportFullBackup());});await page.evaluate(async snapshot=>{await(await import('/src/services/durableStore.ts')).importFullBackup(snapshot);},snapshot);assert.equal((await workspace()).tasks.find(t=>t.title==='提醒回归任务').reminder.enabled,false);
  assert.equal(errors.length,0,errors.join('\n'));console.log('Connections browser: explicit place confirmation, three food sources, g/ml separation, offline labels, mobile layouts, nested back, cross-tab CAS, reload and paused reminder restore passed.');
 }catch(e){await page.screenshot({path:`${out}/connections-failure.png`}).catch(()=>{});throw e;}finally{await browser.close();await server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
