import React,{useEffect,useRef,useState} from 'react';
import type {TaskNode,TaskReminderRule} from '../../types/todo';
import {NativeConnections,loadConnections} from '../../services/connections/store';
import {isAndroid} from '../../services/native/platform';
import {shareTask,openTaskCalendar,sendFeishu,taskShareText,feishuDestination} from '../../services/connections/sharing';
import {ConnectionsDialog} from './ConnectionsPanel';
import './connections.css';
const localTime=(iso:string)=>{const d=new Date(iso);return Number.isFinite(d.getTime())?new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16):'';};
export function TaskReminderEditor(p:{task:TaskNode;path:string;onSave:(rule:TaskReminderRule|null)=>void}) {
 const rule=p.task.reminder;
 const [at,setAt]=useState(localTime(rule?.trigger_at||p.task.due_at||'')),[exact,setExact]=useState(rule?.exact??true),[local,setLocal]=useState(rule?.channels.includes('local')??true),[feishu,setFeishu]=useState(rule?.channels.includes('feishu')??false),[hidden,setHidden]=useState(rule?.hide_title??true),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dialog,setDialog]=useState(false),[allowed,setAllowed]=useState(false),[destination,setDestination]=useState(''),[status,setStatus]=useState<{granted:boolean;exact:boolean;task_channel:boolean}|null>(null),[history,setHistory]=useState<{channel:string;status:string;message:string;at:number}[]|null>(null);
 const lock=useRef(false),request=useRef<AbortController|null>(null);
 useEffect(()=>{let alive=true;const refresh=()=>{loadConnections().then(s=>{if(alive){setAllowed(s.settings.feishu_enabled&&s.settings.feishu_verified);setDestination(s.settings.feishu_label);}}).catch(e=>alive&&setError(e.message));if(isAndroid())NativeConnections.notificationStatus().then(s=>alive&&setStatus(s)).catch(e=>alive&&setError(e.message));};refresh();window.addEventListener('todotree:connections',refresh);window.addEventListener('focus',refresh);return()=>{alive=false;window.removeEventListener('todotree:connections',refresh);window.removeEventListener('focus',refresh);request.current?.abort();};},[]);
 const run=async(action:()=>Promise<string|void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{const message=await action();if(message)setNotice(message);}catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
 const save=()=>{setError('');const time=Date.parse(at);if(!Number.isFinite(time)||time<=Date.now()){setError('选择一个未来的具体提醒时刻');return;}if(!local&&!feishu){setError('至少选择一个提醒渠道');return;}if(feishu&&(!allowed||!isAndroid())){setError('先在 Android 版验证并开启飞书目的地');return;}
  void run(async()=>{const config=feishu?await loadConnections():null;if(feishu&&(!config?.settings.feishu_enabled||!config.settings.feishu_verified||config.settings.feishu_label!==destination))throw Error('飞书配置已改变，请重新核对目的地');const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;p.onSave({enabled:true,trigger_at:new Date(time).toISOString(),timezone,revision:crypto.randomUUID(),exact,channels:[...(local?['local' as const]:[]),...(feishu?['feishu' as const]:[])],hide_title:hidden,...(config?{feishu_destination:await feishuDestination(config)}:{})});return '已提交提醒配置，请确认页面显示“已保存”；权限关闭时仍可能无法提醒';});
 };
 return <section className="reminder-card"><h3>提醒与分享</h3><p className="connection-hint">{rule?.enabled?(Date.parse(rule.trigger_at)<=Date.now()?"提醒时刻已过，可重新选择时间启用":`提醒时间：${new Date(rule.trigger_at).toLocaleString()}`):rule?'提醒已暂停，可重新选择时间启用':'选择具体时刻，截止日期不会自动变成闹钟'}</p><label>提醒时刻 · 当前设备时间（{Intl.DateTimeFormat().resolvedOptions().timeZone}）<input aria-label="待办提醒时刻" type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></label>
 <label className="connection-check"><input type="checkbox" checked={local} onChange={e=>setLocal(e.target.checked)}/>本机通知</label><label className="connection-check"><input type="checkbox" disabled={!allowed||!isAndroid()} checked={feishu} onChange={e=>setFeishu(e.target.checked)}/>飞书 · {destination||'尚未设置目的地'}</label>
 <label className="connection-check"><input type="checkbox" checked={exact} onChange={e=>setExact(e.target.checked)}/>请求准时提醒</label><label className="connection-check"><input type="checkbox" checked={hidden} onChange={e=>setHidden(e.target.checked)}/>通知标题隐藏任务名称</label>
 <p className="connection-hint">{isAndroid()?`本机通知${status?.granted&&status.task_channel?'已开启':'未开启'} · ${status?.exact?'准时权限已开启':'没有准时权限，可能延迟'}`:'网页只保存提醒规则；锁屏通知需使用 Android 安装版。可导入系统日历。'}</p><p className="connection-hint">这是当前这一次待办的提醒；复制任务及下一次重复实例不会沿用旧时刻。</p>
 <div className="reminder-actions"><button className="connection-primary" disabled={busy||p.task.status!=='open'||!!p.task.deleted_at} onClick={save}>保存本次提醒</button>{rule?.enabled&&<button disabled={busy} onClick={()=>{p.onSave({...rule,enabled:false,revision:crypto.randomUUID()});setNotice('已提交暂停请求，请确认任务已保存');}}>暂停提醒</button>}<button onClick={()=>setDialog(true)}>连接与权限</button></div>
 <div className="reminder-actions"><button disabled={busy} onClick={()=>void run(()=>shareTask(p.task,p.path))}>系统分享</button><button disabled={busy} onClick={()=>void run(()=>openTaskCalendar(p.task))}>加入系统日历</button>{allowed&&<button disabled={busy} onClick={()=>void run(async()=>{const config=await loadConnections();if(!config.settings.feishu_enabled||!config.settings.feishu_verified||config.settings.feishu_label!==destination)throw Error('飞书目的地已改变，请重新核对后发送');request.current=new AbortController();await sendFeishu(config,taskShareText(p.task,p.path),request.current.signal);return '飞书接口已接受，请在目的地核对；未发送备注或背景';})}>发送到「{destination}」</button>}</div>
 {isAndroid()&&<button disabled={busy} onClick={()=>void run(async()=>{setHistory((await NativeConnections.taskDelivery({task_id:p.task.id})).rows);})}>查看最近提醒记录</button>}{history&&<div className="connection-hint">{!history.length?'暂无发送记录':history.map((r,i)=><p key={i}>{new Date(r.at).toLocaleString()} · {r.channel==='local'?'本机':'飞书'} · {r.message}</p>)}</div>}
 {error&&<p role="alert" className="connection-error">{error}</p>}{notice&&<p role="status" className="connection-notice">{notice}</p>}{dialog&&<ConnectionsDialog onClose={()=>setDialog(false)}/>}</section>;
}
